{'Package': 'python3-sphinxcontrib.plantuml', 'Source': 'python-sphinxcontrib.plantuml', 'Version': '0.5-5', 'Installed-Size': '34', 'Maintainer': 'Debian OpenStack <openstack-devel@lists.alioth.debian.org>', 'Architecture': 'all', 'Depends': ['plantuml', 'python3-docutils', 'python3-sphinx', ['python3:any', '>=', '3.3.2-2~']], 'Description': 'PlantUML extension for Sphinx - Python 3.x', 'Homepage': 'https://bitbucket.org/birkenfeld/sphinx-contrib', 'Description-md5': 'f502041a994193019aa59f944bf85aa5', 'Section': 'python', 'Priority': 'optional', 'Filename': 'pool/main/p/python-sphinxcontrib.plantuml/python3-sphinxcontrib.plantuml_0.5-5_all.deb', 'Size': '7600', 'SHA256': '063bfd1f9c86b5663db814c9254981a2cfc05f9de23aa776d2750878d60b5949'}